//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/Patrick/Documents/GitHub/p4/Code/Interpreter/Interpreter/Antlr\Dazel.g4 by ANTLR 4.9.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

public partial class DazelLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, WS=6, COMMENT=7, SCREEN=8, ENTITY=9, 
		MOVE_PATTERN=10, MAP=11, ONSCREENENTERED=12, ENTITIES=13, EXITS=14, DATA=15, 
		PATTERN=16, IDENTIFIER=17, INT=18, FLOAT=19, STRING=20, L_PARANTHESIS=21, 
		R_PARANTHESIS=22, L_BRACKET=23, R_BRACKET=24, L_BRACES=25, R_BRACES=26, 
		ASSIGN_OP=27, LESSTHAN_OP=28, GREATERTHAN_OP=29, PLUS_OP=30, MINUS_OP=31, 
		MULTIPLICATION_OP=32, DIVISION_OP=33;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "WS", "COMMENT", "SCREEN", "ENTITY", 
		"MOVE_PATTERN", "MAP", "ONSCREENENTERED", "ENTITIES", "EXITS", "DATA", 
		"PATTERN", "IDENTIFIER", "INT", "FLOAT", "STRING", "L_PARANTHESIS", "R_PARANTHESIS", 
		"L_BRACKET", "R_BRACKET", "L_BRACES", "R_BRACES", "ASSIGN_OP", "LESSTHAN_OP", 
		"GREATERTHAN_OP", "PLUS_OP", "MINUS_OP", "MULTIPLICATION_OP", "DIVISION_OP"
	};


	public DazelLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public DazelLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "';'", "'repeat'", "'if'", "'.'", "','", null, null, "'Screen'", 
		"'Entity'", "'MovePattern'", "'Map'", "'OnScreenEntered'", "'Entities'", 
		"'Exits'", "'Data'", "'Pattern'", null, null, null, null, "'('", "')'", 
		"'['", "']'", "'{'", "'}'", "'='", "'<'", "'>'", "'+'", "'-'", "'*'", 
		"'/'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, "WS", "COMMENT", "SCREEN", "ENTITY", 
		"MOVE_PATTERN", "MAP", "ONSCREENENTERED", "ENTITIES", "EXITS", "DATA", 
		"PATTERN", "IDENTIFIER", "INT", "FLOAT", "STRING", "L_PARANTHESIS", "R_PARANTHESIS", 
		"L_BRACKET", "R_BRACKET", "L_BRACES", "R_BRACES", "ASSIGN_OP", "LESSTHAN_OP", 
		"GREATERTHAN_OP", "PLUS_OP", "MINUS_OP", "MULTIPLICATION_OP", "DIVISION_OP"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Dazel.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static DazelLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '#', '\xEB', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\a', '\x6', '\a', 'W', '\n', '\a', '\r', '\a', '\xE', '\a', 
		'X', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\a', '\b', '\x61', '\n', '\b', '\f', '\b', '\xE', '\b', 
		'\x64', '\v', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', 
		'\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x3', '\x12', 
		'\a', '\x12', '\xB4', '\n', '\x12', '\f', '\x12', '\xE', '\x12', '\xB7', 
		'\v', '\x12', '\x3', '\x13', '\x6', '\x13', '\xBA', '\n', '\x13', '\r', 
		'\x13', '\xE', '\x13', '\xBB', '\x3', '\x14', '\x6', '\x14', '\xBF', '\n', 
		'\x14', '\r', '\x14', '\xE', '\x14', '\xC0', '\x3', '\x14', '\x3', '\x14', 
		'\x6', '\x14', '\xC5', '\n', '\x14', '\r', '\x14', '\xE', '\x14', '\xC6', 
		'\x3', '\x15', '\x3', '\x15', '\a', '\x15', '\xCB', '\n', '\x15', '\f', 
		'\x15', '\xE', '\x15', '\xCE', '\v', '\x15', '\x3', '\x15', '\x3', '\x15', 
		'\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', '\x18', 
		'\x3', '\x18', '\x3', '\x19', '\x3', '\x19', '\x3', '\x1A', '\x3', '\x1A', 
		'\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1D', 
		'\x3', '\x1D', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1F', '\x3', '\x1F', 
		'\x3', ' ', '\x3', ' ', '\x3', '!', '\x3', '!', '\x3', '\"', '\x3', '\"', 
		'\x3', '\xCC', '\x2', '#', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', 
		'\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', 
		'\x15', '\f', '\x17', '\r', '\x19', '\xE', '\x1B', '\xF', '\x1D', '\x10', 
		'\x1F', '\x11', '!', '\x12', '#', '\x13', '%', '\x14', '\'', '\x15', ')', 
		'\x16', '+', '\x17', '-', '\x18', '/', '\x19', '\x31', '\x1A', '\x33', 
		'\x1B', '\x35', '\x1C', '\x37', '\x1D', '\x39', '\x1E', ';', '\x1F', '=', 
		' ', '?', '!', '\x41', '\"', '\x43', '#', '\x3', '\x2', '\a', '\x5', '\x2', 
		'\v', '\f', '\xF', '\xF', '\"', '\"', '\x4', '\x2', '\f', '\f', '\xF', 
		'\xF', '\x4', '\x2', '\x43', '\\', '\x63', '|', '\x6', '\x2', '\x32', 
		';', '\x43', '\\', '\x61', '\x61', '\x63', '|', '\x3', '\x2', '\x32', 
		';', '\x2', '\xF1', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', 
		'\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', '\x2', '\x2', '/', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x31', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x33', '\x3', '\x2', '\x2', '\x2', '\x2', '\x35', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x37', '\x3', '\x2', '\x2', '\x2', '\x2', '\x39', '\x3', 
		'\x2', '\x2', '\x2', '\x2', ';', '\x3', '\x2', '\x2', '\x2', '\x2', '=', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '?', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x41', '\x3', '\x2', '\x2', '\x2', '\x2', '\x43', '\x3', '\x2', '\x2', 
		'\x2', '\x3', '\x45', '\x3', '\x2', '\x2', '\x2', '\x5', 'G', '\x3', '\x2', 
		'\x2', '\x2', '\a', 'N', '\x3', '\x2', '\x2', '\x2', '\t', 'Q', '\x3', 
		'\x2', '\x2', '\x2', '\v', 'S', '\x3', '\x2', '\x2', '\x2', '\r', 'V', 
		'\x3', '\x2', '\x2', '\x2', '\xF', '\\', '\x3', '\x2', '\x2', '\x2', '\x11', 
		'g', '\x3', '\x2', '\x2', '\x2', '\x13', 'n', '\x3', '\x2', '\x2', '\x2', 
		'\x15', 'u', '\x3', '\x2', '\x2', '\x2', '\x17', '\x81', '\x3', '\x2', 
		'\x2', '\x2', '\x19', '\x85', '\x3', '\x2', '\x2', '\x2', '\x1B', '\x95', 
		'\x3', '\x2', '\x2', '\x2', '\x1D', '\x9E', '\x3', '\x2', '\x2', '\x2', 
		'\x1F', '\xA4', '\x3', '\x2', '\x2', '\x2', '!', '\xA9', '\x3', '\x2', 
		'\x2', '\x2', '#', '\xB1', '\x3', '\x2', '\x2', '\x2', '%', '\xB9', '\x3', 
		'\x2', '\x2', '\x2', '\'', '\xBE', '\x3', '\x2', '\x2', '\x2', ')', '\xC8', 
		'\x3', '\x2', '\x2', '\x2', '+', '\xD1', '\x3', '\x2', '\x2', '\x2', '-', 
		'\xD3', '\x3', '\x2', '\x2', '\x2', '/', '\xD5', '\x3', '\x2', '\x2', 
		'\x2', '\x31', '\xD7', '\x3', '\x2', '\x2', '\x2', '\x33', '\xD9', '\x3', 
		'\x2', '\x2', '\x2', '\x35', '\xDB', '\x3', '\x2', '\x2', '\x2', '\x37', 
		'\xDD', '\x3', '\x2', '\x2', '\x2', '\x39', '\xDF', '\x3', '\x2', '\x2', 
		'\x2', ';', '\xE1', '\x3', '\x2', '\x2', '\x2', '=', '\xE3', '\x3', '\x2', 
		'\x2', '\x2', '?', '\xE5', '\x3', '\x2', '\x2', '\x2', '\x41', '\xE7', 
		'\x3', '\x2', '\x2', '\x2', '\x43', '\xE9', '\x3', '\x2', '\x2', '\x2', 
		'\x45', '\x46', '\a', '=', '\x2', '\x2', '\x46', '\x4', '\x3', '\x2', 
		'\x2', '\x2', 'G', 'H', '\a', 't', '\x2', '\x2', 'H', 'I', '\a', 'g', 
		'\x2', '\x2', 'I', 'J', '\a', 'r', '\x2', '\x2', 'J', 'K', '\a', 'g', 
		'\x2', '\x2', 'K', 'L', '\a', '\x63', '\x2', '\x2', 'L', 'M', '\a', 'v', 
		'\x2', '\x2', 'M', '\x6', '\x3', '\x2', '\x2', '\x2', 'N', 'O', '\a', 
		'k', '\x2', '\x2', 'O', 'P', '\a', 'h', '\x2', '\x2', 'P', '\b', '\x3', 
		'\x2', '\x2', '\x2', 'Q', 'R', '\a', '\x30', '\x2', '\x2', 'R', '\n', 
		'\x3', '\x2', '\x2', '\x2', 'S', 'T', '\a', '.', '\x2', '\x2', 'T', '\f', 
		'\x3', '\x2', '\x2', '\x2', 'U', 'W', '\t', '\x2', '\x2', '\x2', 'V', 
		'U', '\x3', '\x2', '\x2', '\x2', 'W', 'X', '\x3', '\x2', '\x2', '\x2', 
		'X', 'V', '\x3', '\x2', '\x2', '\x2', 'X', 'Y', '\x3', '\x2', '\x2', '\x2', 
		'Y', 'Z', '\x3', '\x2', '\x2', '\x2', 'Z', '[', '\b', '\a', '\x2', '\x2', 
		'[', '\xE', '\x3', '\x2', '\x2', '\x2', '\\', ']', '\a', '\x31', '\x2', 
		'\x2', ']', '^', '\a', '\x31', '\x2', '\x2', '^', '\x62', '\x3', '\x2', 
		'\x2', '\x2', '_', '\x61', '\n', '\x3', '\x2', '\x2', '`', '_', '\x3', 
		'\x2', '\x2', '\x2', '\x61', '\x64', '\x3', '\x2', '\x2', '\x2', '\x62', 
		'`', '\x3', '\x2', '\x2', '\x2', '\x62', '\x63', '\x3', '\x2', '\x2', 
		'\x2', '\x63', '\x65', '\x3', '\x2', '\x2', '\x2', '\x64', '\x62', '\x3', 
		'\x2', '\x2', '\x2', '\x65', '\x66', '\b', '\b', '\x2', '\x2', '\x66', 
		'\x10', '\x3', '\x2', '\x2', '\x2', 'g', 'h', '\a', 'U', '\x2', '\x2', 
		'h', 'i', '\a', '\x65', '\x2', '\x2', 'i', 'j', '\a', 't', '\x2', '\x2', 
		'j', 'k', '\a', 'g', '\x2', '\x2', 'k', 'l', '\a', 'g', '\x2', '\x2', 
		'l', 'm', '\a', 'p', '\x2', '\x2', 'm', '\x12', '\x3', '\x2', '\x2', '\x2', 
		'n', 'o', '\a', 'G', '\x2', '\x2', 'o', 'p', '\a', 'p', '\x2', '\x2', 
		'p', 'q', '\a', 'v', '\x2', '\x2', 'q', 'r', '\a', 'k', '\x2', '\x2', 
		'r', 's', '\a', 'v', '\x2', '\x2', 's', 't', '\a', '{', '\x2', '\x2', 
		't', '\x14', '\x3', '\x2', '\x2', '\x2', 'u', 'v', '\a', 'O', '\x2', '\x2', 
		'v', 'w', '\a', 'q', '\x2', '\x2', 'w', 'x', '\a', 'x', '\x2', '\x2', 
		'x', 'y', '\a', 'g', '\x2', '\x2', 'y', 'z', '\a', 'R', '\x2', '\x2', 
		'z', '{', '\a', '\x63', '\x2', '\x2', '{', '|', '\a', 'v', '\x2', '\x2', 
		'|', '}', '\a', 'v', '\x2', '\x2', '}', '~', '\a', 'g', '\x2', '\x2', 
		'~', '\x7F', '\a', 't', '\x2', '\x2', '\x7F', '\x80', '\a', 'p', '\x2', 
		'\x2', '\x80', '\x16', '\x3', '\x2', '\x2', '\x2', '\x81', '\x82', '\a', 
		'O', '\x2', '\x2', '\x82', '\x83', '\a', '\x63', '\x2', '\x2', '\x83', 
		'\x84', '\a', 'r', '\x2', '\x2', '\x84', '\x18', '\x3', '\x2', '\x2', 
		'\x2', '\x85', '\x86', '\a', 'Q', '\x2', '\x2', '\x86', '\x87', '\a', 
		'p', '\x2', '\x2', '\x87', '\x88', '\a', 'U', '\x2', '\x2', '\x88', '\x89', 
		'\a', '\x65', '\x2', '\x2', '\x89', '\x8A', '\a', 't', '\x2', '\x2', '\x8A', 
		'\x8B', '\a', 'g', '\x2', '\x2', '\x8B', '\x8C', '\a', 'g', '\x2', '\x2', 
		'\x8C', '\x8D', '\a', 'p', '\x2', '\x2', '\x8D', '\x8E', '\a', 'G', '\x2', 
		'\x2', '\x8E', '\x8F', '\a', 'p', '\x2', '\x2', '\x8F', '\x90', '\a', 
		'v', '\x2', '\x2', '\x90', '\x91', '\a', 'g', '\x2', '\x2', '\x91', '\x92', 
		'\a', 't', '\x2', '\x2', '\x92', '\x93', '\a', 'g', '\x2', '\x2', '\x93', 
		'\x94', '\a', '\x66', '\x2', '\x2', '\x94', '\x1A', '\x3', '\x2', '\x2', 
		'\x2', '\x95', '\x96', '\a', 'G', '\x2', '\x2', '\x96', '\x97', '\a', 
		'p', '\x2', '\x2', '\x97', '\x98', '\a', 'v', '\x2', '\x2', '\x98', '\x99', 
		'\a', 'k', '\x2', '\x2', '\x99', '\x9A', '\a', 'v', '\x2', '\x2', '\x9A', 
		'\x9B', '\a', 'k', '\x2', '\x2', '\x9B', '\x9C', '\a', 'g', '\x2', '\x2', 
		'\x9C', '\x9D', '\a', 'u', '\x2', '\x2', '\x9D', '\x1C', '\x3', '\x2', 
		'\x2', '\x2', '\x9E', '\x9F', '\a', 'G', '\x2', '\x2', '\x9F', '\xA0', 
		'\a', 'z', '\x2', '\x2', '\xA0', '\xA1', '\a', 'k', '\x2', '\x2', '\xA1', 
		'\xA2', '\a', 'v', '\x2', '\x2', '\xA2', '\xA3', '\a', 'u', '\x2', '\x2', 
		'\xA3', '\x1E', '\x3', '\x2', '\x2', '\x2', '\xA4', '\xA5', '\a', '\x46', 
		'\x2', '\x2', '\xA5', '\xA6', '\a', '\x63', '\x2', '\x2', '\xA6', '\xA7', 
		'\a', 'v', '\x2', '\x2', '\xA7', '\xA8', '\a', '\x63', '\x2', '\x2', '\xA8', 
		' ', '\x3', '\x2', '\x2', '\x2', '\xA9', '\xAA', '\a', 'R', '\x2', '\x2', 
		'\xAA', '\xAB', '\a', '\x63', '\x2', '\x2', '\xAB', '\xAC', '\a', 'v', 
		'\x2', '\x2', '\xAC', '\xAD', '\a', 'v', '\x2', '\x2', '\xAD', '\xAE', 
		'\a', 'g', '\x2', '\x2', '\xAE', '\xAF', '\a', 't', '\x2', '\x2', '\xAF', 
		'\xB0', '\a', 'p', '\x2', '\x2', '\xB0', '\"', '\x3', '\x2', '\x2', '\x2', 
		'\xB1', '\xB5', '\t', '\x4', '\x2', '\x2', '\xB2', '\xB4', '\t', '\x5', 
		'\x2', '\x2', '\xB3', '\xB2', '\x3', '\x2', '\x2', '\x2', '\xB4', '\xB7', 
		'\x3', '\x2', '\x2', '\x2', '\xB5', '\xB3', '\x3', '\x2', '\x2', '\x2', 
		'\xB5', '\xB6', '\x3', '\x2', '\x2', '\x2', '\xB6', '$', '\x3', '\x2', 
		'\x2', '\x2', '\xB7', '\xB5', '\x3', '\x2', '\x2', '\x2', '\xB8', '\xBA', 
		'\t', '\x6', '\x2', '\x2', '\xB9', '\xB8', '\x3', '\x2', '\x2', '\x2', 
		'\xBA', '\xBB', '\x3', '\x2', '\x2', '\x2', '\xBB', '\xB9', '\x3', '\x2', 
		'\x2', '\x2', '\xBB', '\xBC', '\x3', '\x2', '\x2', '\x2', '\xBC', '&', 
		'\x3', '\x2', '\x2', '\x2', '\xBD', '\xBF', '\t', '\x6', '\x2', '\x2', 
		'\xBE', '\xBD', '\x3', '\x2', '\x2', '\x2', '\xBF', '\xC0', '\x3', '\x2', 
		'\x2', '\x2', '\xC0', '\xBE', '\x3', '\x2', '\x2', '\x2', '\xC0', '\xC1', 
		'\x3', '\x2', '\x2', '\x2', '\xC1', '\xC2', '\x3', '\x2', '\x2', '\x2', 
		'\xC2', '\xC4', '\a', '\x30', '\x2', '\x2', '\xC3', '\xC5', '\t', '\x6', 
		'\x2', '\x2', '\xC4', '\xC3', '\x3', '\x2', '\x2', '\x2', '\xC5', '\xC6', 
		'\x3', '\x2', '\x2', '\x2', '\xC6', '\xC4', '\x3', '\x2', '\x2', '\x2', 
		'\xC6', '\xC7', '\x3', '\x2', '\x2', '\x2', '\xC7', '(', '\x3', '\x2', 
		'\x2', '\x2', '\xC8', '\xCC', '\a', '$', '\x2', '\x2', '\xC9', '\xCB', 
		'\v', '\x2', '\x2', '\x2', '\xCA', '\xC9', '\x3', '\x2', '\x2', '\x2', 
		'\xCB', '\xCE', '\x3', '\x2', '\x2', '\x2', '\xCC', '\xCD', '\x3', '\x2', 
		'\x2', '\x2', '\xCC', '\xCA', '\x3', '\x2', '\x2', '\x2', '\xCD', '\xCF', 
		'\x3', '\x2', '\x2', '\x2', '\xCE', '\xCC', '\x3', '\x2', '\x2', '\x2', 
		'\xCF', '\xD0', '\a', '$', '\x2', '\x2', '\xD0', '*', '\x3', '\x2', '\x2', 
		'\x2', '\xD1', '\xD2', '\a', '*', '\x2', '\x2', '\xD2', ',', '\x3', '\x2', 
		'\x2', '\x2', '\xD3', '\xD4', '\a', '+', '\x2', '\x2', '\xD4', '.', '\x3', 
		'\x2', '\x2', '\x2', '\xD5', '\xD6', '\a', ']', '\x2', '\x2', '\xD6', 
		'\x30', '\x3', '\x2', '\x2', '\x2', '\xD7', '\xD8', '\a', '_', '\x2', 
		'\x2', '\xD8', '\x32', '\x3', '\x2', '\x2', '\x2', '\xD9', '\xDA', '\a', 
		'}', '\x2', '\x2', '\xDA', '\x34', '\x3', '\x2', '\x2', '\x2', '\xDB', 
		'\xDC', '\a', '\x7F', '\x2', '\x2', '\xDC', '\x36', '\x3', '\x2', '\x2', 
		'\x2', '\xDD', '\xDE', '\a', '?', '\x2', '\x2', '\xDE', '\x38', '\x3', 
		'\x2', '\x2', '\x2', '\xDF', '\xE0', '\a', '>', '\x2', '\x2', '\xE0', 
		':', '\x3', '\x2', '\x2', '\x2', '\xE1', '\xE2', '\a', '@', '\x2', '\x2', 
		'\xE2', '<', '\x3', '\x2', '\x2', '\x2', '\xE3', '\xE4', '\a', '-', '\x2', 
		'\x2', '\xE4', '>', '\x3', '\x2', '\x2', '\x2', '\xE5', '\xE6', '\a', 
		'/', '\x2', '\x2', '\xE6', '@', '\x3', '\x2', '\x2', '\x2', '\xE7', '\xE8', 
		'\a', ',', '\x2', '\x2', '\xE8', '\x42', '\x3', '\x2', '\x2', '\x2', '\xE9', 
		'\xEA', '\a', '\x31', '\x2', '\x2', '\xEA', '\x44', '\x3', '\x2', '\x2', 
		'\x2', '\n', '\x2', 'X', '\x62', '\xB5', '\xBB', '\xC0', '\xC6', '\xCC', 
		'\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
