//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Dazel.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="DazelParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IDazelVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStart([NotNull] DazelParser.StartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.game_object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGame_object([NotNull] DazelParser.Game_objectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.empty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmpty([NotNull] DazelParser.EmptyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.game_object_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGame_object_type([NotNull] DazelParser.Game_object_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.game_object_contents"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGame_object_contents([NotNull] DazelParser.Game_object_contentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.game_object_content"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGame_object_content([NotNull] DazelParser.Game_object_contentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.content_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContent_type([NotNull] DazelParser.Content_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.statement_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement_list([NotNull] DazelParser.Statement_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] DazelParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.repeat_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRepeat_loop([NotNull] DazelParser.Repeat_loopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_statement([NotNull] DazelParser.If_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] DazelParser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] DazelParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.sum_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSum_expression([NotNull] DazelParser.Sum_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.factor_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactor_expression([NotNull] DazelParser.Factor_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.terminal_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerminal_expression([NotNull] DazelParser.Terminal_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.sum_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSum_operation([NotNull] DazelParser.Sum_operationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.factor_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactor_operation([NotNull] DazelParser.Factor_operationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.function_invocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_invocation([NotNull] DazelParser.Function_invocationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.member_access"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMember_access([NotNull] DazelParser.Member_accessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.value_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue_list([NotNull] DazelParser.Value_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue([NotNull] DazelParser.ValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray([NotNull] DazelParser.ArrayContext context);
}
