//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/Patrick/Documents/GitHub/p4/Code/Interpreter/Interpreter/Antlr\Dazel.g4 by ANTLR 4.9.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="DazelParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.1")]
[System.CLSCompliant(false)]
internal interface IDazelVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStart([NotNull] DazelParser.StartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.gameObject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGameObject([NotNull] DazelParser.GameObjectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.gameObjectBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGameObjectBlock([NotNull] DazelParser.GameObjectBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.empty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmpty([NotNull] DazelParser.EmptyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.gameObjectContents"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGameObjectContents([NotNull] DazelParser.GameObjectContentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.gameObjectContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGameObjectContent([NotNull] DazelParser.GameObjectContentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.statementList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatementList([NotNull] DazelParser.StatementListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.statementBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatementBlock([NotNull] DazelParser.StatementBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] DazelParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.repeatLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRepeatLoop([NotNull] DazelParser.RepeatLoopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStatement([NotNull] DazelParser.IfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.statementExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatementExpression([NotNull] DazelParser.StatementExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] DazelParser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] DazelParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.sumExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSumExpression([NotNull] DazelParser.SumExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.factorExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactorExpression([NotNull] DazelParser.FactorExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.terminalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerminalExpression([NotNull] DazelParser.TerminalExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.sumOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSumOperation([NotNull] DazelParser.SumOperationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.factorOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactorOperation([NotNull] DazelParser.FactorOperationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.functionInvocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionInvocation([NotNull] DazelParser.FunctionInvocationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.memberAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberAccess([NotNull] DazelParser.MemberAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.valueList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValueList([NotNull] DazelParser.ValueListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue([NotNull] DazelParser.ValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DazelParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray([NotNull] DazelParser.ArrayContext context);
}
