//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:/Mapper/Tools/Dev/Projects/p4/Code/Interpreter/Interpreter/Antlr\Dazel.g4 by ANTLR 4.9.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.1")]
[System.CLSCompliant(false)]
public partial class DazelParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, WS=12, IDENTIFIER=13, INT=14, FLOAT=15, SCREEN=16, 
		ENTITY=17, MOVE_PATTERN=18, L_PARANTHESIS=19, R_PARANTHESIS=20, L_BRACKET=21, 
		R_BRACKET=22, L_BRACES=23, R_BRACES=24, ASSIGN_OP=25, LESSTHAN_OP=26, 
		GREATERTHAN_OP=27, PLUS_OP=28, MINUS_OP=29, MULTIPLICATION_OP=30, DIVISION_OP=31, 
		QUOTATION_MARK=32;
	public const int
		RULE_start = 0, RULE_gameObject = 1, RULE_empty = 2, RULE_gameObjectContents = 3, 
		RULE_gameObjectContent = 4, RULE_screenContentType = 5, RULE_entityContentType = 6, 
		RULE_movePatternContentType = 7, RULE_statementList = 8, RULE_statement = 9, 
		RULE_repeatLoop = 10, RULE_ifStatement = 11, RULE_statementExpression = 12, 
		RULE_assignment = 13, RULE_expression = 14, RULE_sumExpression = 15, RULE_factorExpression = 16, 
		RULE_terminalExpression = 17, RULE_sumOperation = 18, RULE_factorOperation = 19, 
		RULE_functionInvocation = 20, RULE_memberAccess = 21, RULE_valueList = 22, 
		RULE_value = 23, RULE_array = 24;
	public static readonly string[] ruleNames = {
		"start", "gameObject", "empty", "gameObjectContents", "gameObjectContent", 
		"screenContentType", "entityContentType", "movePatternContentType", "statementList", 
		"statement", "repeatLoop", "ifStatement", "statementExpression", "assignment", 
		"expression", "sumExpression", "factorExpression", "terminalExpression", 
		"sumOperation", "factorOperation", "functionInvocation", "memberAccess", 
		"valueList", "value", "array"
	};

	private static readonly string[] _LiteralNames = {
		null, "'Map'", "'OnScreenEntered'", "'Entities'", "'Exits'", "'Data'", 
		"'Pattern'", "';'", "'repeat'", "'if'", "'.'", "','", null, null, null, 
		null, "'Screen '", "'Entity '", "'MovePattern '", "'('", "')'", "'['", 
		"']'", "'{'", "'}'", "'='", "'<'", "'>'", "'+'", "'-'", "'*'", "'/'", 
		"'\"'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		"WS", "IDENTIFIER", "INT", "FLOAT", "SCREEN", "ENTITY", "MOVE_PATTERN", 
		"L_PARANTHESIS", "R_PARANTHESIS", "L_BRACKET", "R_BRACKET", "L_BRACES", 
		"R_BRACES", "ASSIGN_OP", "LESSTHAN_OP", "GREATERTHAN_OP", "PLUS_OP", "MINUS_OP", 
		"MULTIPLICATION_OP", "DIVISION_OP", "QUOTATION_MARK"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Dazel.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static DazelParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public DazelParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public DazelParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class StartContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public GameObjectContext gameObject() {
			return GetRuleContext<GameObjectContext>(0);
		}
		public StartContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_start; } }
	}

	[RuleVersion(0)]
	public StartContext start() {
		StartContext _localctx = new StartContext(Context, State);
		EnterRule(_localctx, 0, RULE_start);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 50;
			gameObject();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class GameObjectContext : ParserRuleContext {
		public IToken gameObjectType;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(DazelParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode L_BRACES() { return GetToken(DazelParser.L_BRACES, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public GameObjectContentsContext gameObjectContents() {
			return GetRuleContext<GameObjectContentsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode R_BRACES() { return GetToken(DazelParser.R_BRACES, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SCREEN() { return GetToken(DazelParser.SCREEN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ENTITY() { return GetToken(DazelParser.ENTITY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MOVE_PATTERN() { return GetToken(DazelParser.MOVE_PATTERN, 0); }
		public GameObjectContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_gameObject; } }
	}

	[RuleVersion(0)]
	public GameObjectContext gameObject() {
		GameObjectContext _localctx = new GameObjectContext(Context, State);
		EnterRule(_localctx, 2, RULE_gameObject);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 52;
			_localctx.gameObjectType = TokenStream.LT(1);
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << SCREEN) | (1L << ENTITY) | (1L << MOVE_PATTERN))) != 0)) ) {
				_localctx.gameObjectType = ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 53;
			Match(IDENTIFIER);
			State = 54;
			Match(L_BRACES);
			State = 55;
			gameObjectContents();
			State = 56;
			Match(R_BRACES);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EmptyContext : ParserRuleContext {
		public EmptyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_empty; } }
	}

	[RuleVersion(0)]
	public EmptyContext empty() {
		EmptyContext _localctx = new EmptyContext(Context, State);
		EnterRule(_localctx, 4, RULE_empty);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class GameObjectContentsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public GameObjectContentContext gameObjectContent() {
			return GetRuleContext<GameObjectContentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public GameObjectContentsContext gameObjectContents() {
			return GetRuleContext<GameObjectContentsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public EmptyContext empty() {
			return GetRuleContext<EmptyContext>(0);
		}
		public GameObjectContentsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_gameObjectContents; } }
	}

	[RuleVersion(0)]
	public GameObjectContentsContext gameObjectContents() {
		GameObjectContentsContext _localctx = new GameObjectContentsContext(Context, State);
		EnterRule(_localctx, 6, RULE_gameObjectContents);
		try {
			State = 65;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,0,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 60;
				gameObjectContent();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 61;
				gameObjectContent();
				State = 62;
				gameObjectContents();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 64;
				empty();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class GameObjectContentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ScreenContentTypeContext screenContentType() {
			return GetRuleContext<ScreenContentTypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode L_BRACES() { return GetToken(DazelParser.L_BRACES, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StatementListContext statementList() {
			return GetRuleContext<StatementListContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode R_BRACES() { return GetToken(DazelParser.R_BRACES, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public EntityContentTypeContext entityContentType() {
			return GetRuleContext<EntityContentTypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public MovePatternContentTypeContext movePatternContentType() {
			return GetRuleContext<MovePatternContentTypeContext>(0);
		}
		public GameObjectContentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_gameObjectContent; } }
	}

	[RuleVersion(0)]
	public GameObjectContentContext gameObjectContent() {
		GameObjectContentContext _localctx = new GameObjectContentContext(Context, State);
		EnterRule(_localctx, 8, RULE_gameObjectContent);
		try {
			State = 82;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__0:
			case T__1:
			case T__2:
			case T__3:
				EnterOuterAlt(_localctx, 1);
				{
				State = 67;
				screenContentType();
				State = 68;
				Match(L_BRACES);
				State = 69;
				statementList();
				State = 70;
				Match(R_BRACES);
				}
				break;
			case T__4:
				EnterOuterAlt(_localctx, 2);
				{
				State = 72;
				entityContentType();
				State = 73;
				Match(L_BRACES);
				State = 74;
				statementList();
				State = 75;
				Match(R_BRACES);
				}
				break;
			case T__5:
				EnterOuterAlt(_localctx, 3);
				{
				State = 77;
				movePatternContentType();
				State = 78;
				Match(L_BRACES);
				State = 79;
				statementList();
				State = 80;
				Match(R_BRACES);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ScreenContentTypeContext : ParserRuleContext {
		public ScreenContentTypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_screenContentType; } }
	}

	[RuleVersion(0)]
	public ScreenContentTypeContext screenContentType() {
		ScreenContentTypeContext _localctx = new ScreenContentTypeContext(Context, State);
		EnterRule(_localctx, 10, RULE_screenContentType);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 84;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__0) | (1L << T__1) | (1L << T__2) | (1L << T__3))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EntityContentTypeContext : ParserRuleContext {
		public EntityContentTypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_entityContentType; } }
	}

	[RuleVersion(0)]
	public EntityContentTypeContext entityContentType() {
		EntityContentTypeContext _localctx = new EntityContentTypeContext(Context, State);
		EnterRule(_localctx, 12, RULE_entityContentType);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 86;
			Match(T__4);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MovePatternContentTypeContext : ParserRuleContext {
		public MovePatternContentTypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_movePatternContentType; } }
	}

	[RuleVersion(0)]
	public MovePatternContentTypeContext movePatternContentType() {
		MovePatternContentTypeContext _localctx = new MovePatternContentTypeContext(Context, State);
		EnterRule(_localctx, 14, RULE_movePatternContentType);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 88;
			Match(T__5);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementListContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement() {
			return GetRuleContext<StatementContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementListContext statementList() {
			return GetRuleContext<StatementListContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public EmptyContext empty() {
			return GetRuleContext<EmptyContext>(0);
		}
		public StatementListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statementList; } }
	}

	[RuleVersion(0)]
	public StatementListContext statementList() {
		StatementListContext _localctx = new StatementListContext(Context, State);
		EnterRule(_localctx, 16, RULE_statementList);
		try {
			State = 98;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,2,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 90;
				statement();
				State = 91;
				Match(T__6);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 93;
				statement();
				State = 94;
				Match(T__6);
				State = 95;
				statementList();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 97;
				empty();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public RepeatLoopContext repeatLoop() {
			return GetRuleContext<RepeatLoopContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public IfStatementContext ifStatement() {
			return GetRuleContext<IfStatementContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementExpressionContext statementExpression() {
			return GetRuleContext<StatementExpressionContext>(0);
		}
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 18, RULE_statement);
		try {
			State = 103;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__7:
				EnterOuterAlt(_localctx, 1);
				{
				State = 100;
				repeatLoop();
				}
				break;
			case T__8:
				EnterOuterAlt(_localctx, 2);
				{
				State = 101;
				ifStatement();
				}
				break;
			case IDENTIFIER:
				EnterOuterAlt(_localctx, 3);
				{
				State = 102;
				statementExpression();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RepeatLoopContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode L_BRACES() { return GetToken(DazelParser.L_BRACES, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StatementListContext statementList() {
			return GetRuleContext<StatementListContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode R_BRACES() { return GetToken(DazelParser.R_BRACES, 0); }
		public RepeatLoopContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_repeatLoop; } }
	}

	[RuleVersion(0)]
	public RepeatLoopContext repeatLoop() {
		RepeatLoopContext _localctx = new RepeatLoopContext(Context, State);
		EnterRule(_localctx, 20, RULE_repeatLoop);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 105;
			Match(T__7);
			State = 106;
			Match(L_BRACES);
			State = 107;
			statementList();
			State = 108;
			Match(R_BRACES);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IfStatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode L_BRACES() { return GetToken(DazelParser.L_BRACES, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StatementListContext statementList() {
			return GetRuleContext<StatementListContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode R_BRACES() { return GetToken(DazelParser.R_BRACES, 0); }
		public IfStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ifStatement; } }
	}

	[RuleVersion(0)]
	public IfStatementContext ifStatement() {
		IfStatementContext _localctx = new IfStatementContext(Context, State);
		EnterRule(_localctx, 22, RULE_ifStatement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 110;
			Match(T__8);
			State = 111;
			expression();
			State = 112;
			Match(L_BRACES);
			State = 113;
			statementList();
			State = 114;
			Match(R_BRACES);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public AssignmentContext assignment() {
			return GetRuleContext<AssignmentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionInvocationContext functionInvocation() {
			return GetRuleContext<FunctionInvocationContext>(0);
		}
		public StatementExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statementExpression; } }
	}

	[RuleVersion(0)]
	public StatementExpressionContext statementExpression() {
		StatementExpressionContext _localctx = new StatementExpressionContext(Context, State);
		EnterRule(_localctx, 24, RULE_statementExpression);
		try {
			State = 118;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 116;
				assignment();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 117;
				functionInvocation();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AssignmentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(DazelParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASSIGN_OP() { return GetToken(DazelParser.ASSIGN_OP, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public AssignmentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assignment; } }
	}

	[RuleVersion(0)]
	public AssignmentContext assignment() {
		AssignmentContext _localctx = new AssignmentContext(Context, State);
		EnterRule(_localctx, 26, RULE_assignment);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 120;
			Match(IDENTIFIER);
			State = 121;
			Match(ASSIGN_OP);
			State = 122;
			expression();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public SumExpressionContext sumExpression() {
			return GetRuleContext<SumExpressionContext>(0);
		}
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		ExpressionContext _localctx = new ExpressionContext(Context, State);
		EnterRule(_localctx, 28, RULE_expression);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 124;
			sumExpression(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SumExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public FactorExpressionContext factorExpression() {
			return GetRuleContext<FactorExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SumExpressionContext sumExpression() {
			return GetRuleContext<SumExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SumOperationContext sumOperation() {
			return GetRuleContext<SumOperationContext>(0);
		}
		public SumExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_sumExpression; } }
	}

	[RuleVersion(0)]
	public SumExpressionContext sumExpression() {
		return sumExpression(0);
	}

	private SumExpressionContext sumExpression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		SumExpressionContext _localctx = new SumExpressionContext(Context, _parentState);
		SumExpressionContext _prevctx = _localctx;
		int _startState = 30;
		EnterRecursionRule(_localctx, 30, RULE_sumExpression, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			State = 127;
			factorExpression(0);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 135;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,5,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new SumExpressionContext(_parentctx, _parentState);
					PushNewRecursionContext(_localctx, _startState, RULE_sumExpression);
					State = 129;
					if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
					State = 130;
					sumOperation();
					State = 131;
					factorExpression(0);
					}
					} 
				}
				State = 137;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,5,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class FactorExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TerminalExpressionContext terminalExpression() {
			return GetRuleContext<TerminalExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public FactorExpressionContext factorExpression() {
			return GetRuleContext<FactorExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public FactorOperationContext factorOperation() {
			return GetRuleContext<FactorOperationContext>(0);
		}
		public FactorExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_factorExpression; } }
	}

	[RuleVersion(0)]
	public FactorExpressionContext factorExpression() {
		return factorExpression(0);
	}

	private FactorExpressionContext factorExpression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		FactorExpressionContext _localctx = new FactorExpressionContext(Context, _parentState);
		FactorExpressionContext _prevctx = _localctx;
		int _startState = 32;
		EnterRecursionRule(_localctx, 32, RULE_factorExpression, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			State = 139;
			terminalExpression();
			}
			Context.Stop = TokenStream.LT(-1);
			State = 147;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,6,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new FactorExpressionContext(_parentctx, _parentState);
					PushNewRecursionContext(_localctx, _startState, RULE_factorExpression);
					State = 141;
					if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
					State = 142;
					factorOperation();
					State = 143;
					terminalExpression();
					}
					} 
				}
				State = 149;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,6,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class TerminalExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode L_PARANTHESIS() { return GetToken(DazelParser.L_PARANTHESIS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode R_PARANTHESIS() { return GetToken(DazelParser.R_PARANTHESIS, 0); }
		public TerminalExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_terminalExpression; } }
	}

	[RuleVersion(0)]
	public TerminalExpressionContext terminalExpression() {
		TerminalExpressionContext _localctx = new TerminalExpressionContext(Context, State);
		EnterRule(_localctx, 34, RULE_terminalExpression);
		try {
			State = 155;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case IDENTIFIER:
			case INT:
			case FLOAT:
			case L_BRACKET:
				EnterOuterAlt(_localctx, 1);
				{
				State = 150;
				value();
				}
				break;
			case L_PARANTHESIS:
				EnterOuterAlt(_localctx, 2);
				{
				State = 151;
				Match(L_PARANTHESIS);
				State = 152;
				expression();
				State = 153;
				Match(R_PARANTHESIS);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SumOperationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PLUS_OP() { return GetToken(DazelParser.PLUS_OP, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MINUS_OP() { return GetToken(DazelParser.MINUS_OP, 0); }
		public SumOperationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_sumOperation; } }
	}

	[RuleVersion(0)]
	public SumOperationContext sumOperation() {
		SumOperationContext _localctx = new SumOperationContext(Context, State);
		EnterRule(_localctx, 36, RULE_sumOperation);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 157;
			_la = TokenStream.LA(1);
			if ( !(_la==PLUS_OP || _la==MINUS_OP) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FactorOperationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MULTIPLICATION_OP() { return GetToken(DazelParser.MULTIPLICATION_OP, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DIVISION_OP() { return GetToken(DazelParser.DIVISION_OP, 0); }
		public FactorOperationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_factorOperation; } }
	}

	[RuleVersion(0)]
	public FactorOperationContext factorOperation() {
		FactorOperationContext _localctx = new FactorOperationContext(Context, State);
		EnterRule(_localctx, 38, RULE_factorOperation);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 159;
			_la = TokenStream.LA(1);
			if ( !(_la==MULTIPLICATION_OP || _la==DIVISION_OP) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionInvocationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(DazelParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode L_PARANTHESIS() { return GetToken(DazelParser.L_PARANTHESIS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ValueListContext valueList() {
			return GetRuleContext<ValueListContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode R_PARANTHESIS() { return GetToken(DazelParser.R_PARANTHESIS, 0); }
		public FunctionInvocationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionInvocation; } }
	}

	[RuleVersion(0)]
	public FunctionInvocationContext functionInvocation() {
		FunctionInvocationContext _localctx = new FunctionInvocationContext(Context, State);
		EnterRule(_localctx, 40, RULE_functionInvocation);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 161;
			Match(IDENTIFIER);
			State = 162;
			Match(L_PARANTHESIS);
			State = 163;
			valueList();
			State = 164;
			Match(R_PARANTHESIS);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MemberAccessContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] IDENTIFIER() { return GetTokens(DazelParser.IDENTIFIER); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER(int i) {
			return GetToken(DazelParser.IDENTIFIER, i);
		}
		public MemberAccessContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_memberAccess; } }
	}

	[RuleVersion(0)]
	public MemberAccessContext memberAccess() {
		MemberAccessContext _localctx = new MemberAccessContext(Context, State);
		EnterRule(_localctx, 42, RULE_memberAccess);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 166;
			Match(IDENTIFIER);
			State = 167;
			Match(T__9);
			State = 168;
			Match(IDENTIFIER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ValueListContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ValueListContext valueList() {
			return GetRuleContext<ValueListContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public EmptyContext empty() {
			return GetRuleContext<EmptyContext>(0);
		}
		public ValueListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_valueList; } }
	}

	[RuleVersion(0)]
	public ValueListContext valueList() {
		ValueListContext _localctx = new ValueListContext(Context, State);
		EnterRule(_localctx, 44, RULE_valueList);
		try {
			State = 176;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,8,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 170;
				value();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 171;
				value();
				State = 172;
				Match(T__10);
				State = 173;
				valueList();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 175;
				empty();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ValueContext : ParserRuleContext {
		public IToken terminalValue;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(DazelParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT() { return GetToken(DazelParser.INT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FLOAT() { return GetToken(DazelParser.FLOAT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ArrayContext array() {
			return GetRuleContext<ArrayContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public MemberAccessContext memberAccess() {
			return GetRuleContext<MemberAccessContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionInvocationContext functionInvocation() {
			return GetRuleContext<FunctionInvocationContext>(0);
		}
		public ValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_value; } }
	}

	[RuleVersion(0)]
	public ValueContext value() {
		ValueContext _localctx = new ValueContext(Context, State);
		EnterRule(_localctx, 46, RULE_value);
		int _la;
		try {
			State = 182;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,9,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 178;
				_localctx.terminalValue = TokenStream.LT(1);
				_la = TokenStream.LA(1);
				if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << IDENTIFIER) | (1L << INT) | (1L << FLOAT))) != 0)) ) {
					_localctx.terminalValue = ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 179;
				array();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 180;
				memberAccess();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 181;
				functionInvocation();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArrayContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode L_BRACKET() { return GetToken(DazelParser.L_BRACKET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ValueListContext valueList() {
			return GetRuleContext<ValueListContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode R_BRACKET() { return GetToken(DazelParser.R_BRACKET, 0); }
		public ArrayContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_array; } }
	}

	[RuleVersion(0)]
	public ArrayContext array() {
		ArrayContext _localctx = new ArrayContext(Context, State);
		EnterRule(_localctx, 48, RULE_array);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 184;
			Match(L_BRACKET);
			State = 185;
			valueList();
			State = 186;
			Match(R_BRACKET);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 15: return sumExpression_sempred((SumExpressionContext)_localctx, predIndex);
		case 16: return factorExpression_sempred((FactorExpressionContext)_localctx, predIndex);
		}
		return true;
	}
	private bool sumExpression_sempred(SumExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 2);
		}
		return true;
	}
	private bool factorExpression_sempred(FactorExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 1: return Precpred(Context, 2);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\"', '\xBF', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x5', 
		'\x5', '\x44', '\n', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\x5', '\x6', 'U', '\n', '\x6', '\x3', '\a', 
		'\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x5', '\n', '\x65', '\n', '\n', '\x3', '\v', 
		'\x3', '\v', '\x3', '\v', '\x5', '\v', 'j', '\n', '\v', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', 
		'\xE', '\x5', '\xE', 'y', '\n', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', 
		'\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x11', '\a', '\x11', '\x88', '\n', '\x11', '\f', '\x11', '\xE', '\x11', 
		'\x8B', '\v', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\a', '\x12', '\x94', 
		'\n', '\x12', '\f', '\x12', '\xE', '\x12', '\x97', '\v', '\x12', '\x3', 
		'\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x5', 
		'\x13', '\x9E', '\n', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', '\x15', 
		'\x3', '\x15', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', 
		'\x3', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', 
		'\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', 
		'\x3', '\x18', '\x5', '\x18', '\xB3', '\n', '\x18', '\x3', '\x19', '\x3', 
		'\x19', '\x3', '\x19', '\x3', '\x19', '\x5', '\x19', '\xB9', '\n', '\x19', 
		'\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', 
		'\x2', '\x4', ' ', '\"', '\x1B', '\x2', '\x4', '\x6', '\b', '\n', '\f', 
		'\xE', '\x10', '\x12', '\x14', '\x16', '\x18', '\x1A', '\x1C', '\x1E', 
		' ', '\"', '$', '&', '(', '*', ',', '.', '\x30', '\x32', '\x2', '\a', 
		'\x3', '\x2', '\x12', '\x14', '\x3', '\x2', '\x3', '\x6', '\x3', '\x2', 
		'\x1E', '\x1F', '\x3', '\x2', ' ', '!', '\x3', '\x2', '\xF', '\x11', '\x2', 
		'\xB6', '\x2', '\x34', '\x3', '\x2', '\x2', '\x2', '\x4', '\x36', '\x3', 
		'\x2', '\x2', '\x2', '\x6', '<', '\x3', '\x2', '\x2', '\x2', '\b', '\x43', 
		'\x3', '\x2', '\x2', '\x2', '\n', 'T', '\x3', '\x2', '\x2', '\x2', '\f', 
		'V', '\x3', '\x2', '\x2', '\x2', '\xE', 'X', '\x3', '\x2', '\x2', '\x2', 
		'\x10', 'Z', '\x3', '\x2', '\x2', '\x2', '\x12', '\x64', '\x3', '\x2', 
		'\x2', '\x2', '\x14', 'i', '\x3', '\x2', '\x2', '\x2', '\x16', 'k', '\x3', 
		'\x2', '\x2', '\x2', '\x18', 'p', '\x3', '\x2', '\x2', '\x2', '\x1A', 
		'x', '\x3', '\x2', '\x2', '\x2', '\x1C', 'z', '\x3', '\x2', '\x2', '\x2', 
		'\x1E', '~', '\x3', '\x2', '\x2', '\x2', ' ', '\x80', '\x3', '\x2', '\x2', 
		'\x2', '\"', '\x8C', '\x3', '\x2', '\x2', '\x2', '$', '\x9D', '\x3', '\x2', 
		'\x2', '\x2', '&', '\x9F', '\x3', '\x2', '\x2', '\x2', '(', '\xA1', '\x3', 
		'\x2', '\x2', '\x2', '*', '\xA3', '\x3', '\x2', '\x2', '\x2', ',', '\xA8', 
		'\x3', '\x2', '\x2', '\x2', '.', '\xB2', '\x3', '\x2', '\x2', '\x2', '\x30', 
		'\xB8', '\x3', '\x2', '\x2', '\x2', '\x32', '\xBA', '\x3', '\x2', '\x2', 
		'\x2', '\x34', '\x35', '\x5', '\x4', '\x3', '\x2', '\x35', '\x3', '\x3', 
		'\x2', '\x2', '\x2', '\x36', '\x37', '\t', '\x2', '\x2', '\x2', '\x37', 
		'\x38', '\a', '\xF', '\x2', '\x2', '\x38', '\x39', '\a', '\x19', '\x2', 
		'\x2', '\x39', ':', '\x5', '\b', '\x5', '\x2', ':', ';', '\a', '\x1A', 
		'\x2', '\x2', ';', '\x5', '\x3', '\x2', '\x2', '\x2', '<', '=', '\x3', 
		'\x2', '\x2', '\x2', '=', '\a', '\x3', '\x2', '\x2', '\x2', '>', '\x44', 
		'\x5', '\n', '\x6', '\x2', '?', '@', '\x5', '\n', '\x6', '\x2', '@', '\x41', 
		'\x5', '\b', '\x5', '\x2', '\x41', '\x44', '\x3', '\x2', '\x2', '\x2', 
		'\x42', '\x44', '\x5', '\x6', '\x4', '\x2', '\x43', '>', '\x3', '\x2', 
		'\x2', '\x2', '\x43', '?', '\x3', '\x2', '\x2', '\x2', '\x43', '\x42', 
		'\x3', '\x2', '\x2', '\x2', '\x44', '\t', '\x3', '\x2', '\x2', '\x2', 
		'\x45', '\x46', '\x5', '\f', '\a', '\x2', '\x46', 'G', '\a', '\x19', '\x2', 
		'\x2', 'G', 'H', '\x5', '\x12', '\n', '\x2', 'H', 'I', '\a', '\x1A', '\x2', 
		'\x2', 'I', 'U', '\x3', '\x2', '\x2', '\x2', 'J', 'K', '\x5', '\xE', '\b', 
		'\x2', 'K', 'L', '\a', '\x19', '\x2', '\x2', 'L', 'M', '\x5', '\x12', 
		'\n', '\x2', 'M', 'N', '\a', '\x1A', '\x2', '\x2', 'N', 'U', '\x3', '\x2', 
		'\x2', '\x2', 'O', 'P', '\x5', '\x10', '\t', '\x2', 'P', 'Q', '\a', '\x19', 
		'\x2', '\x2', 'Q', 'R', '\x5', '\x12', '\n', '\x2', 'R', 'S', '\a', '\x1A', 
		'\x2', '\x2', 'S', 'U', '\x3', '\x2', '\x2', '\x2', 'T', '\x45', '\x3', 
		'\x2', '\x2', '\x2', 'T', 'J', '\x3', '\x2', '\x2', '\x2', 'T', 'O', '\x3', 
		'\x2', '\x2', '\x2', 'U', '\v', '\x3', '\x2', '\x2', '\x2', 'V', 'W', 
		'\t', '\x3', '\x2', '\x2', 'W', '\r', '\x3', '\x2', '\x2', '\x2', 'X', 
		'Y', '\a', '\a', '\x2', '\x2', 'Y', '\xF', '\x3', '\x2', '\x2', '\x2', 
		'Z', '[', '\a', '\b', '\x2', '\x2', '[', '\x11', '\x3', '\x2', '\x2', 
		'\x2', '\\', ']', '\x5', '\x14', '\v', '\x2', ']', '^', '\a', '\t', '\x2', 
		'\x2', '^', '\x65', '\x3', '\x2', '\x2', '\x2', '_', '`', '\x5', '\x14', 
		'\v', '\x2', '`', '\x61', '\a', '\t', '\x2', '\x2', '\x61', '\x62', '\x5', 
		'\x12', '\n', '\x2', '\x62', '\x65', '\x3', '\x2', '\x2', '\x2', '\x63', 
		'\x65', '\x5', '\x6', '\x4', '\x2', '\x64', '\\', '\x3', '\x2', '\x2', 
		'\x2', '\x64', '_', '\x3', '\x2', '\x2', '\x2', '\x64', '\x63', '\x3', 
		'\x2', '\x2', '\x2', '\x65', '\x13', '\x3', '\x2', '\x2', '\x2', '\x66', 
		'j', '\x5', '\x16', '\f', '\x2', 'g', 'j', '\x5', '\x18', '\r', '\x2', 
		'h', 'j', '\x5', '\x1A', '\xE', '\x2', 'i', '\x66', '\x3', '\x2', '\x2', 
		'\x2', 'i', 'g', '\x3', '\x2', '\x2', '\x2', 'i', 'h', '\x3', '\x2', '\x2', 
		'\x2', 'j', '\x15', '\x3', '\x2', '\x2', '\x2', 'k', 'l', '\a', '\n', 
		'\x2', '\x2', 'l', 'm', '\a', '\x19', '\x2', '\x2', 'm', 'n', '\x5', '\x12', 
		'\n', '\x2', 'n', 'o', '\a', '\x1A', '\x2', '\x2', 'o', '\x17', '\x3', 
		'\x2', '\x2', '\x2', 'p', 'q', '\a', '\v', '\x2', '\x2', 'q', 'r', '\x5', 
		'\x1E', '\x10', '\x2', 'r', 's', '\a', '\x19', '\x2', '\x2', 's', 't', 
		'\x5', '\x12', '\n', '\x2', 't', 'u', '\a', '\x1A', '\x2', '\x2', 'u', 
		'\x19', '\x3', '\x2', '\x2', '\x2', 'v', 'y', '\x5', '\x1C', '\xF', '\x2', 
		'w', 'y', '\x5', '*', '\x16', '\x2', 'x', 'v', '\x3', '\x2', '\x2', '\x2', 
		'x', 'w', '\x3', '\x2', '\x2', '\x2', 'y', '\x1B', '\x3', '\x2', '\x2', 
		'\x2', 'z', '{', '\a', '\xF', '\x2', '\x2', '{', '|', '\a', '\x1B', '\x2', 
		'\x2', '|', '}', '\x5', '\x1E', '\x10', '\x2', '}', '\x1D', '\x3', '\x2', 
		'\x2', '\x2', '~', '\x7F', '\x5', ' ', '\x11', '\x2', '\x7F', '\x1F', 
		'\x3', '\x2', '\x2', '\x2', '\x80', '\x81', '\b', '\x11', '\x1', '\x2', 
		'\x81', '\x82', '\x5', '\"', '\x12', '\x2', '\x82', '\x89', '\x3', '\x2', 
		'\x2', '\x2', '\x83', '\x84', '\f', '\x4', '\x2', '\x2', '\x84', '\x85', 
		'\x5', '&', '\x14', '\x2', '\x85', '\x86', '\x5', '\"', '\x12', '\x2', 
		'\x86', '\x88', '\x3', '\x2', '\x2', '\x2', '\x87', '\x83', '\x3', '\x2', 
		'\x2', '\x2', '\x88', '\x8B', '\x3', '\x2', '\x2', '\x2', '\x89', '\x87', 
		'\x3', '\x2', '\x2', '\x2', '\x89', '\x8A', '\x3', '\x2', '\x2', '\x2', 
		'\x8A', '!', '\x3', '\x2', '\x2', '\x2', '\x8B', '\x89', '\x3', '\x2', 
		'\x2', '\x2', '\x8C', '\x8D', '\b', '\x12', '\x1', '\x2', '\x8D', '\x8E', 
		'\x5', '$', '\x13', '\x2', '\x8E', '\x95', '\x3', '\x2', '\x2', '\x2', 
		'\x8F', '\x90', '\f', '\x4', '\x2', '\x2', '\x90', '\x91', '\x5', '(', 
		'\x15', '\x2', '\x91', '\x92', '\x5', '$', '\x13', '\x2', '\x92', '\x94', 
		'\x3', '\x2', '\x2', '\x2', '\x93', '\x8F', '\x3', '\x2', '\x2', '\x2', 
		'\x94', '\x97', '\x3', '\x2', '\x2', '\x2', '\x95', '\x93', '\x3', '\x2', 
		'\x2', '\x2', '\x95', '\x96', '\x3', '\x2', '\x2', '\x2', '\x96', '#', 
		'\x3', '\x2', '\x2', '\x2', '\x97', '\x95', '\x3', '\x2', '\x2', '\x2', 
		'\x98', '\x9E', '\x5', '\x30', '\x19', '\x2', '\x99', '\x9A', '\a', '\x15', 
		'\x2', '\x2', '\x9A', '\x9B', '\x5', '\x1E', '\x10', '\x2', '\x9B', '\x9C', 
		'\a', '\x16', '\x2', '\x2', '\x9C', '\x9E', '\x3', '\x2', '\x2', '\x2', 
		'\x9D', '\x98', '\x3', '\x2', '\x2', '\x2', '\x9D', '\x99', '\x3', '\x2', 
		'\x2', '\x2', '\x9E', '%', '\x3', '\x2', '\x2', '\x2', '\x9F', '\xA0', 
		'\t', '\x4', '\x2', '\x2', '\xA0', '\'', '\x3', '\x2', '\x2', '\x2', '\xA1', 
		'\xA2', '\t', '\x5', '\x2', '\x2', '\xA2', ')', '\x3', '\x2', '\x2', '\x2', 
		'\xA3', '\xA4', '\a', '\xF', '\x2', '\x2', '\xA4', '\xA5', '\a', '\x15', 
		'\x2', '\x2', '\xA5', '\xA6', '\x5', '.', '\x18', '\x2', '\xA6', '\xA7', 
		'\a', '\x16', '\x2', '\x2', '\xA7', '+', '\x3', '\x2', '\x2', '\x2', '\xA8', 
		'\xA9', '\a', '\xF', '\x2', '\x2', '\xA9', '\xAA', '\a', '\f', '\x2', 
		'\x2', '\xAA', '\xAB', '\a', '\xF', '\x2', '\x2', '\xAB', '-', '\x3', 
		'\x2', '\x2', '\x2', '\xAC', '\xB3', '\x5', '\x30', '\x19', '\x2', '\xAD', 
		'\xAE', '\x5', '\x30', '\x19', '\x2', '\xAE', '\xAF', '\a', '\r', '\x2', 
		'\x2', '\xAF', '\xB0', '\x5', '.', '\x18', '\x2', '\xB0', '\xB3', '\x3', 
		'\x2', '\x2', '\x2', '\xB1', '\xB3', '\x5', '\x6', '\x4', '\x2', '\xB2', 
		'\xAC', '\x3', '\x2', '\x2', '\x2', '\xB2', '\xAD', '\x3', '\x2', '\x2', 
		'\x2', '\xB2', '\xB1', '\x3', '\x2', '\x2', '\x2', '\xB3', '/', '\x3', 
		'\x2', '\x2', '\x2', '\xB4', '\xB9', '\t', '\x6', '\x2', '\x2', '\xB5', 
		'\xB9', '\x5', '\x32', '\x1A', '\x2', '\xB6', '\xB9', '\x5', ',', '\x17', 
		'\x2', '\xB7', '\xB9', '\x5', '*', '\x16', '\x2', '\xB8', '\xB4', '\x3', 
		'\x2', '\x2', '\x2', '\xB8', '\xB5', '\x3', '\x2', '\x2', '\x2', '\xB8', 
		'\xB6', '\x3', '\x2', '\x2', '\x2', '\xB8', '\xB7', '\x3', '\x2', '\x2', 
		'\x2', '\xB9', '\x31', '\x3', '\x2', '\x2', '\x2', '\xBA', '\xBB', '\a', 
		'\x17', '\x2', '\x2', '\xBB', '\xBC', '\x5', '.', '\x18', '\x2', '\xBC', 
		'\xBD', '\a', '\x18', '\x2', '\x2', '\xBD', '\x33', '\x3', '\x2', '\x2', 
		'\x2', '\f', '\x43', 'T', '\x64', 'i', 'x', '\x89', '\x95', '\x9D', '\xB2', 
		'\xB8',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
