name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      working-directory: ./code/Interpreter
      run: dotnet restore
    - name: Build
      working-directory: ./code/Interpreter
      run: cd ./code/Interpreter && dotnet build --no-restore
    - name: Test
      working-directory: ./code/Interpreter
      run: cd ./code/Interpreter && dotnet test --no-build --verbosity normal
